### PR TITLE
npm scoped packages support

### PR DESCRIPTION
**Pull request by cstamas**
This change adds scope support for npm repositories and also replaces metadata store from Orient to
repo LS. No migration path present, hence is usable for new deploys only.

ITs and tests updated.

### CODE REVIEW

**Comment by mcculls** [comment]
Since this PR doesn't provide an upgrade or migration path wouldn't it be better done as an alternative plugin rather than replacing the existing plugin which would break anyone currently using it?

**Comment by mosabua** [comment]
Imho it would be good to have an upgrade path. It might be even a simple one that just purges the orient db and recreates the data for the new storage. Unless I am mistaken no critical data is in the orient db anyway... 

Having two different npm support plugins seems like a bad idea.

**Comment by cstamas** [comment]
Agreed, will add then upgrade step for this one...

**Comment by cstamas** [comment]
Changes:
* migration added
* Orient plugin is optional for npm plugin to work (needed only during migration)

Steps to migrate:
* only hosted repositories are getting migrated (no proxies and groups)
* start up latest NX, hosted npm repositories will appear "empty" (only tarballs)
* create Migrate hosted npm metadata (may have one task for "all" npm reposes, or multiple tasks to have them migrate in parallel). Start them, wait for all to finish.
* Check results. If all fine, remove tasks, stop nexus, remove Orient plugin, restart.

And there it is, you have scope support and migrated packages. Have fun!

**Comment by cstamas** [comment]
Added commit acf2c5422c02f619ed8d3fd6fcb54056a208ec8a  that fixes several problems regarding remote access (NEXUS-9238) and other....

**Comment by cstamas** [comment]
Synced more Takari changes:

Improvements:
* introduce routing to npm groups (the good ol' Routing, so be able to INCLUDE, EXCLUDE
by scope, name or anything)
* implement proper transport overload detection, hence NX respond with 503 Service unavailable instead
of 500 Server Error in case of overload

Bugfixes:
* npm proxy should return cached content in case it is present and remote misbehaves

**Comment by kellyrob99** [comment]
Note: need to consider this carefully for planned NX2->NX3 upgrade as it also affects where/how npm metadata is stored

**Comment by cstamas** [comment]
Synced more Takari changes:
* npm group is write-thru, so npm tool needs only one URL to get packages but also to publish. Publishing happens to first npm hosted member group has.

**Comment by kellyrob99** [comment]
Scoped package support ended up being formally added in 2.14.4 so this should no longer be necessary, https://issues.sonatype.org/browse/NEXUS-6857

**Pull request closed without merging**
