### PR TITLE
Fix to apply proxy authentication

### PR DESCRIPTION
**Pull request by kazuki43zoo**
I've fixed the [NEXUS-10502](https://issues.sonatype.org/browse/NEXUS-10502).
Please review this fix.

### CODE REVIEW

**Comment by kellyrob99** [comment]
Tracking internally at https://issues.sonatype.org/browse/NEXUS-11890

**Comment by DarthHater** [comment]
Unfortunately this did not fix the issue @kazuki43zoo , but we currently have a fix in progress internally. Closing this issue, follow the JIRA issue for more information.

**Comment by kazuki43zoo** [comment]
Hi @DarthHater , thanks for reply.

>  but we currently have a fix in progress internally. Closing this issue, follow the JIRA issue for more information.

I will expect an early release !!

**Comment by wwannemacher** [comment]
Hello @kazuki43zoo - please reopen this PR, your fix is the correct fix for the issue (ref: https://issues.sonatype.org/browse/NEXUS-10502)

**Comment by kazuki43zoo** [comment]
Hi @wwannemacher , I've submitted new PR via gh-23.

**Pull request closed without merging**
