### PR TITLE
[NEXUS-28889] Added ZStd for control files compressed with a modern algo

### PR DESCRIPTION
**Pull request by derjohn**
I have no clue if that piece of code works or does even compile. It's just for reference in https://issues.sonatype.org/browse/NEXUS-28889

### CODE REVIEW

**Comment by marcominetti** [comment]
Please merge asap, it's breaking the feature for upcoming release of Ubuntu.

To test you can use the libc6 2.34 package from ubuntu 21.10 as example.

**Comment by derjohn** [comment]
@marcominetti See: https://issues.sonatype.org/browse/NEXUS-28889 to "Upvote", I think SonaType switch die Jira for Issues (that's sad, but it's true).

**Comment by ikus060** [comment]
Could we get some progress for this issue ?

**Comment by derjohn** [comment]
@ikus060 I think the Sonatype people only read their Jira Task tracker. Since Vista Equity is behind Sona https://www.sonatype.com/investors/vista-equity-partners?smtNoRedir=1  ..... non commercial things have slowed down.... </oppinion>

**Comment by gracecllee** [comment]
Hi, thanks everyone for your comments on this thread. This ticket has been raised in priority within Sonatype and there will be a team assigned to address this. Thanks!

**Comment by derjohn** [comment]
has been resvoled. testes with 3.38.

**Pull request closed without merging**
