### PR TITLE
[NEXUS-23968] OrientPyPiHostedFacet should delete TempBlob on getIndex

### PR DESCRIPTION
**Pull request by pstoellberger**
`StorageFacet.createTempBlob` should be called using try block to automatically dispose of tempBlob resource

### CODE REVIEW

**Review by sergeyonofreychuck — APPROVED** [review]

**Review by mlukaretkyi — APPROVED** [review]

**Review by aornatovskyy — APPROVED** [review]

**Comment by doddi** [comment]
Thanks for the contribution @pstoellberger, before we can merge could I ask you to [sign the Sonatype Contributor License Agreement](https://sonatypecla.herokuapp.com/sign-cla)

**Comment by pstoellberger** [comment]
done

**Comment by doddi** [comment]
@pstoellberger this is now merged internally, should make it's way out to nexus-public soon. Thanks again for the contribution

**Comment by doddi** [comment]
Closing this PR as now merged internally

**Pull request closed without merging**
