### PR TITLE
Fix(npm-repository) Can't update latest dist-tag manually  

### PR DESCRIPTION
**Pull request by rluvaton**
Fix [NEXUS-22915](https://issues.sonatype.org/browse/NEXUS-22915)

### CODE REVIEW

**Comment by rluvaton** [comment]
Actually, the npm behavior for the latest version is not latest by **semver**, but rather latest by **date**.

**Comment by jlestes** [comment]
It would be great to get this resolved. I've currently run into an issue with `semantic-release` that it has issues when promoting a version from another channel to latest. For example a pre-release on `dist-tag` of `next` will fail to promote to `dist-tag` of `latest`. The command that is executed which fails and I believe this PR would resolve is `npm dist-tag add @scope/name@1.1.0 latest`.

**Comment by rluvaton** [comment]
> It would be great to get this resolved. I've currently run into an issue with `semantic-release` that it has issues when promoting a version from another channel to latest. For example a pre-release on `dist-tag` of `next` will fail to promote to `dist-tag` of `latest`. The command that is executed which fails and I believe this PR would resolve is `npm dist-tag add @scope/name@1.1.0 latest`. 

@jlestes What we did in our company meanwhile is that I build the npm registry jar file and replace it with the jar file in the nexus directory

**Comment by peterlynch** [comment]
Thank you for your contribution.

The `npm dist-tag` command is not intended to update the latest tag of an npm package - hence why the test is present in the first place. Making NXRM allow it to do that would make NXRM act differently than what the npm maintainers intend, and also act differently than the official registry.

I'm not saying that allowing the latest tag to be altered somehow can't have a valid use case, just that using `dist-tag` command is not it. In the meantime to alter what the latest tag points at in a hosted repository, one should simply re-publish what you want to be "latest" to that hosted repository.

 Please refer to updated description of https://issues.sonatype.org/browse/NEXUS-22915 for more details.

**Comment by jlestes** [comment]
@peterlynch Thanks for the reply. Wouldn't republishing an artifact with the same version to latest then create an issue where the version in Nexus now has a new integrity SHA therefore breaking any consumers of the package that was published under another dist-tag? This command from my understanding is more about promoting an already published artifact to another distribution channel. Please correct me if I am incorrect about the package integrity information.

**Comment by rluvaton** [comment]
Thank you for the reply.


> **The `npm dist-tag` command is not intended to update the latest tag of an npm package** - hence why the test is present in the first place. Making NXRM allow it to do that would make NXRM act differently than what the npm maintainers intend, and also act differently than the official registry.


If you meant that you **can't** change `latest` using `dist-tags` I don't think you are right
> Here I change my package `latest` in the official registry
output


If you meant another thing I'll be happy for an explanation.

**Comment by rluvaton** [comment]
@peterlynch so, what do you say?

**Comment by RomainPhil** [comment]
it will be neccessary for us to,  with [semantic release](https://github.com/semantic-release/github) it actually break the ci when the tag latest is normally update with last package version.

can this issue be re opened ?

**Comment by rluvaton** [comment]
Why this isn't taking seriously?

**Comment by RomainPhil** [comment]
Any news @peterlynch ?
 Cause for the moment, we need semantic release to  success where it could raise some important issueand update the tag latest  manually wich is a feature supported by default with npm repository as  rluvaton make the demonstration.

**Comment by rluvaton** [comment]
Hey @timlevett,I created this PR to add missing functionality that exist in the official NPM registry, but it seems like it's hard to reach your colleagues to take a second look, can you please take a look at this PR and comment  what do you think the state of this PR (will it ever get merged, or not) is?

Thank you

**Comment by webketje** [comment]
@peterlynch I find no reference online to back up this claim:
> The npm dist-tag command is not intended to update the latest tag of an npm package

Authors of the Yarn pkg manager tried arguing along those lines [here](https://github.com/npm/feedback/discussions/109), but the ensuing discussion highlights how problematic this assumption is.
As mentioned by Alan Wood in [NEXUS-22915](https://issues.sonatype.org/browse/NEXUS-22915), "latest" in the npm ecosystem is just the default tag. And it also is in the docker ecosystem. For better, and worse. As I understand from the acceptance criteria in NEXUS-22915, even when this issue is resolved, Nexus' NPM registry behavior will still significantly diverge from NPM's:

> Adding a new release will (still) set the latest tag to that release (it can then be moved by applying latest to another release).

Meaning when you do `npm publish mylib --tag beta` it will magically be tagged `latest` which is IMO super-dangerous when you have triggers set up to rebuild with latest (which some people argue against, fair enough), and means authors should adjust their pipelines to do something like: 

```bash
PREV_LATEST_VER=$(npm info mylib version)
npm publish mylib --tag anyotherthanlatest
npm dist-tag add mylib@$PREV_LATEST_VER latest
```

For those readers who find this a very bad idea, you have 2 options:
* treat a different tag as "latest" eg "stable", and don't ever use "latest"
* use another tool for a private npm pkg registry

**Pull request closed without merging**
