### PR TITLE
Nokazuki

### PR DESCRIPTION
**Pull request by cstamas**
Get rid of Kazuki, that is anyway unused on runtime. If upgrade needed, one can upgrade
to 2.13.0 and from there to NX with this change.

### CODE REVIEW

**Comment by adreghiciu** [comment]
+1

**Comment by mcculls** [comment]
This only shaves ~1.7mb of optional content from the final distribution, which as you say is only active when upgrading from certain releases and will be unused from then onwards. I'm not convinced that saving is worth forcing people using those releases to upgrade in two steps.

**Comment by cstamas** [comment]
@mcculls My intention is not really to shave distro size or remove KZ 
completely (as KZ is used by analytics too AFAIR), but instead to make them 
(KZ, H2, etc) ​_removable_​ from a customized/minimal distro, to lessen the 
cohesion of plugins. To increase the "manoeuvre space" when it comes to selecting
needed plugins to install in a distro...

**Comment by mcculls** [comment]
Personally I'd prefer a PR that made the Kazuki references truly optional at runtime without removing them. It should be possible to use try...catch blocks and/or reflection to allow Nexus to start without the nexus-kazuki-plugin that doesn't break upgrade.

**Comment by cstamas** [comment]
Agreed, but according to current state of NX PM the "optional" plugin dependency is not implemented, hence, without orient being present for plugin manager to resolve it will prevent capabilities plugin to be loaded, no?

**Comment by mcculls** [comment]
@cstamas support for optional plugin dependencies was added in https://github.com/sonatype/nexus-plugin-bundle/pull/8 so you can declare an optional dependency to the `nexus-kazuki-plugin` as long as you use the 1.3-SNAPSHOT of the `nexus-plugin-bundle-maven-plugin`

**Comment by cstamas** [comment]
I saw that, but current plugin manager code does not allow optional plugin dependencies, does it?

**Comment by cstamas** [comment]
Replaced by https://github.com/sonatype/nexus-public/pull/8

**Pull request closed without merging**
