### PR TITLE
remove non-printable characters from version

### PR DESCRIPTION
**Pull request by reven404**
This pr fix the same problem as #52 , use remove non-printable character instead of trim .

### CODE REVIEW

**Comment by lixiaoyu** [comment]
Hello,for it has not been merged yet, it there a way building the project manually or some other way to solve it temporarily? @reven404

**Comment by sergeyonofreychuck** [comment]
@reven404  The fix is OK. But for consistency I think the Name field is a good candidate to remove not printable characters.

**Comment by reven404** [comment]
> @reven404 The fix is OK. But for consistency I think the Name field is a good candidate to remove not printable characters.

+name

**Comment by sergeyonofreychuck** [comment]
@reven404 could you please give the pod name and the version that have such problem with not printable characters.

**Comment by reven404** [comment]
> @reven404 could you please give the pod name and the version that have such problem with not printable characters.
@sergeyonofreychuck you can see 
[RealmSwift.podspec.json](https://github.com/CocoaPods/Specs/blob/master/Specs/9/4/5/RealmSwift/0.92.2/RealmSwift.podspec.json).

**Comment by sergeyonofreychuck** [comment]
The fix will be available in Nexus 3.23.0 and Nexus Public after the next sync.

**Pull request merged**
