### PR TITLE
Fix to apply proxy authentication

### PR DESCRIPTION
**Pull request by kazuki43zoo**
I've fixed the [NEXUS-10502](https://issues.sonatype.org/browse/NEXUS-10502).
Please review this fix.

Related with gh-17.

### CODE REVIEW

**Comment by wwannemacher** [comment]
@kazuki43zoo - going through some internal steps, code review, etc. Once completed, I will close this PR but reference it in our internal repo...

**Comment by DarthHater** [comment]
Thanks @kazuki43zoo for helping us out, we appreciate it!

**Comment by wwannemacher** [comment]
thanks again, @kazuki43zoo - merged into internal repo!!

**Comment by kazuki43zoo** [comment]
@wwannemacher , GJ 👍

**Comment by DarthHater** [comment]
@kazuki43zoo you should expect to see the fix make it out into this repo in approx a week, if you've been relying on it.

**Pull request closed without merging**
