### PR TITLE
[nexus 2.x] no boot delegation

### PR DESCRIPTION
**Pull request by adreghiciu**
Replace Nexus 2 boot delegation "*" with packages being exported by system bundle and plugins using DynamicImport-Package.

This will allow plugins to include as dependencies different versions of libraries that are also present in nexus core.

### CODE REVIEW

**Comment by cstamas** [comment]
+1

**Comment by jdillon** [comment]
why do you need this?  seems pretty fragile configuration

**Comment by adreghiciu** [comment]
@jdillon By doing boot delegation, class loading will first look in the boot class loader and te boot class loader is the class loader that loads nexus core. This means that plugins cannot include in their dependencies any class that is also in core/core dependencies. This means that if my plugin needs another version of jackson or guava for example as needed by elastic search I cannot do that. Prior osgi version of nexus 2, this was working correctly.

**Comment by jdillon** [comment]
@adreghiciu still seems pretty fragile configuration, easy to break whenever something in core changes, and easy to forget to update or miss something important that would otherwise break things.

/me shrugs

**Pull request closed without merging**
